### ISSUE TITLE
Python linear regression package with statistical tests focus

### ISSUE THREAD

**Issue by tirthajyoti** [rouseguy/intro2stats#10]
In your linear regression Notebook, you mentioned about scikit-learn, but as we know that does not have good statistical tests for the linear regression (residual analysis or F-test etc. like R does).

I have developed a lightweight package called `MLR` which mixes the simple fit and predict of the scikit-learn package with statistical inference and residual analysis.

You can refer to it or use it in your Notebooks if you like. **[Here are the docs](https://mlr.readthedocs.io/en/latest/)**.

**Comment by eliekawerk** [comment]
Thanks for that! Definitely a nice library to add to my set of tools!

Elie Kawerk, PhD
Data Scientist
eliekawerk.weebly.com | +961 70 95 40 83

________________________________

**Comment by tirthajyoti** [comment]
Cool! Thanks and I am closing this issue now.
