### ISSUE TITLE
Installing requirements is throwing error for functools

### ISSUE THREAD

**Issue by taranjeet** [rouseguy/intro2stats#2]
I am running Ubuntu 14.04 64 bit on a machine with Python 2.7 in the venv. Whenever I am trying to install requirements.txt or requirements_linux.txt, I am getting the following error

```
Could not find a version that satisfies the requirement functools32==3.2.3.post2 (from -r requirements.txt (line 6)) (from versions: 3.2.3-1, 3.2.3-1, 3.2.3-2, 3.2.3-2)
```

I bypassed this error by simply writing 

```
functools32==3.2.3-2
```

I think both the requirements should be updated or is just a error specific to my machine only?

**Comment by raghothams** [comment]
I too have an Ubuntu 14.04 64bit OS, I created the virtualenv but I don't get this error. I still have `functools32==3.2.3.post2` in the requirements file.

**Comment by rouseguy** [comment]
I checked on Ubuntu 14.04 on an AWS instance. And I didn't face an issue with `functools32==3.2.3.post2` version. Works fine.

**Comment by jeffwillette** [comment]
I am having this problem as well with a 14.04 digital ocean instance

**Comment by rouseguy** [comment]
We re-wrote most of the notebooks for Python 3 here
https://github.com/amitkaps/hackermath

That's a much better version than what's available here. Please look into that and see if works.

**Comment by jeffwillette** [comment]
It turns out it was a pip issue, I had made a new virtual environment with python2.7 and for some reason it doesn't work until pip is upgraded
